### ISSUE TITLE
Conda Install Fails - ResolvePackageNotFound: - ipython==7.9.0=py37h5ca1d4c_0

### ISSUE THREAD

**Issue by samjsilva91** [simonom/PyCHAM#11]
**Current Behavior:**
Install from conda fails using conda 4.8.2

**Step to reproduce:**
Run conda env create -f PyCHAM_macenv.yml -n PyCHAM using the current version of the PyCHAM_macenv.yml file. 

**Error Message:**
Solving environment: failed

ResolvePackageNotFound:
  - ipython==7.9.0=py37h5ca1d4c_0

**Expected Behavior:**
PyCHAM and dependencies are installed.

**Comment by simonom** [comment]
Thanks @samjsilva91 , looking into this now

**Comment by simonom** [comment]
Successfully replicated error, investigating resolution

**Comment by simonom** [comment]
Resolution found @samjsilva91 , as documented in the change log the specification of the ipython version was removed; now conda will install the most appropriate ipython available.  Installation runs fine now on my machine, so will close this issue soon.
