### ISSUE TITLE
Improve output file metadata

### ISSUE THREAD

**Issue by samjsilva91** [simonom/PyCHAM#12]
Would it be possible to improve the metadata contained within the output files? I see this as a potentially large limiting factor in the wide usability of this model, which would be a shame. 

File names like 'x' and 'y' aren't very informative, and the lack of metadata associated with the files (e.g. column names, units, etc.) make the interpretation of the results require more expert knowledge of the code than is ideal. Other modern box models (e.g. AtChem2), output a text file that has a bit more information than what I've found using and modifying the example code.

**Comment by simonom** [comment]
Great idea, working on it now

**Comment by simonom** [comment]
I've gone for a more information is better approach in the file names of outputs and their contained metadata.  Additionally, I included component names inside the previously titled 'constants' output.  This required updates to several modules.  Will close this issue unless further suggestions available.  Thanks for the idea :)
