### ISSUE TITLE
Chemical Scheme .xml file - available on MCM?

### ISSUE THREAD

**Issue by baongocthai** [simonom/PyCHAM#17]
Hi Simon,
Is the .xml file downloaded from MCM? Or it has to be written ourselves? If it's the latter case, would you know a fast way to write such files - given the number of species involved in 1 VOC can be rather large (>1000 species)? Thanks!

**Comment by simonom** [comment]
Dear baongocthai,

Yes, it can be downloaded from the MCM website, for a given MCM subset you can select the xml output format.

There are examples of xml file in the examples folder and instructions of how to adapt xml files to any chemical scheme modifications in the README.

Thanks for getting in contact.

Kind regards,
Simon O'Meara

National Centre for Atmospheric Science Postdoctoral Research Associate
________________________________
From: baongocthai ***@***.***>
Sent: 01 June 2021 04:11
To: simonom/PyCHAM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [simonom/PyCHAM] Chemical Scheme .xml file - available on MCM? (#17)


Hi Simon,
Is the .xml file downloaded from MCM? Or it has to be written ourselves? If it's the latter case, would you know a fast way to write such files - given the number of species involved in 1 VOC can be rather large (>1000 species)? Thanks!
