### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by dhhagan** [simonom/PyCHAM#4]
The [JOSS submission][1] is for v0.0.5, but the current GitHub version is 0.2.2 - this should be reconciled on the JOSS submission.

[1]: https://github.com/openjournals/joss-reviews/issues/1918

**Comment by simonom** [comment]
Hi @dhhagan 
I don't know how to do this, any tips?

**Comment by dhhagan** [comment]
Hey @simonom I think we can just ping the editor and they will update it. Best to do this as the last step in case any more changes need to be made.
